### ISSUE TITLE
Webpack Package Error

### ISSUE THREAD

**Issue by jtherrien-accuraty** [Accuraty/AccuTheme#37]
PS C:\GitHubLocal\EMP2022> npm run package

> accutheme@1.0.0 package
> webpack --config webpack.installer.config.js

[webpack-cli] Failed to load 'C:\GitHubLocal\EMP2022\webpack.installer.config.js' config
[webpack-cli] TypeError: Cannot read properties of undefined (reading 'trim')
    at isTrue (file:///C:/GitHubLocal/EMP2022/gulpfileDir/utils/isTrue.js:4:15)
    at file:///C:/GitHubLocal/EMP2022/gulpfileDir/config/project.js:20:22
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async WebpackCLI.tryRequireThenImport (C:\GitHubLocal\EMP2022\node_modules\webpack-cli\lib\webpack-cli.js:57:26)
    at async WebpackCLI.loadConfig (C:\GitHubLocal\EMP2022\node_modules\webpack-cli\lib\webpack-cli.js:1554:23)
    at async Promise.all (index 0)
    at async WebpackCLI.resolveConfig (C:\GitHubLocal\EMP2022\node_modules\webpack-cli\lib\webpack-cli.js:1608:35)

**Comment by jtherrien-accuraty** [comment]
Already fixed in EMP2022

**Comment by jtherrien-accuraty** [comment]
Fixed
